repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict

  - repo: https://github.com/ddanier/sub-pre-commit.git
    rev: v2.21.0
    hooks:
      - id: sub-pre-commit
        alias: web
        name: "pre-commit for web"
        args: [ "-p", "web" ]
        files: "^web.*"

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - "@team23/commitlint-config@1.0.0"

default_stages:
  - commit

default_install_hook_types:
  - pre-commit
  - commit-msg
