/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArticleListResponseDataItemAttributesHeroimageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy } from './articleListResponseDataItemAttributesHeroimageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy';
import { ArticleListResponseDataItemAttributesHeroimage } from './articleListResponseDataItemAttributesHeroimage';
import { ArticleListResponseDataItemAttributesHeroimageDataAttributesFolderDataAttributesParent } from './articleListResponseDataItemAttributesHeroimageDataAttributesFolderDataAttributesParent';


export interface ArticleListResponseDataItemAttributes { 
    title?: string;
    description?: string;
    body?: string;
    heroimage?: ArticleListResponseDataItemAttributesHeroimage;
    footertext?: string;
    createdAt?: string;
    updatedAt?: string;
    publishedAt?: string;
    createdBy?: ArticleListResponseDataItemAttributesHeroimageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy;
    updatedBy?: ArticleListResponseDataItemAttributesHeroimageDataAttributesFolderDataAttributesParent;
}

