/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Enum } from './enum';


export interface UsersPermissionsRolesPost200Response { 
    ok?: UsersPermissionsRolesPost200Response.OkEnum;
}
export namespace UsersPermissionsRolesPost200Response {
    export type OkEnum = 'true';
    export const OkEnum = {
        True: 'true' as OkEnum
    };
}


