/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissions } from './usersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissions';
import { UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsers } from './usersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsers';
import { ArticleListResponseDataItemAttributesHeroimageDataAttributesFolderDataAttributesParent } from './articleListResponseDataItemAttributesHeroimageDataAttributesFolderDataAttributesParent';


export interface UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributes { 
    name?: string;
    description?: string;
    type?: string;
    permissions?: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissions;
    users?: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsers;
    createdAt?: string;
    updatedAt?: string;
    createdBy?: ArticleListResponseDataItemAttributesHeroimageDataAttributesFolderDataAttributesParent;
    updatedBy?: ArticleListResponseDataItemAttributesHeroimageDataAttributesFolderDataAttributesParent;
}

